/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const RESET_MESSAGE = 'RESET_MESSAGE';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const CONFIRM_REGISTER_USER = 'CONFIRM_REGISTER_USER';
export const CONFIRM_REGISTER_USER_SUCCESS = 'CONFIRM_REGISTER_USER_SUCCESS';
export const CONFIRM_REGISTER_USER_ERROR = 'CONFIRM_REGISTER_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const RESEND_CONFIRMATION_CODE = 'RESEND_CONFIRMATION_CODE';
export const RESEND_CONFIRMATION_CODE_SUCCESS =
  'RESEND_CONFIRMATION_CODE_SUCCESS';
export const RESEND_CONFIRMATION_CODE_ERROR = 'RESEND_CONFIRMATION_CODE_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const FORGOT_PASSWORD_SUBMIT = 'FORGOT_PASSWORD_SUBMIT';
export const FORGOT_PASSWORD_SUBMIT_SUCCESS = 'FORGOT_PASSWORD_SUBMIT_SUCCESS';
export const FORGOT_PASSWORD_SUBMIT_ERROR = 'FORGOT_PASSWORD_SUBMIT_ERROR';

export const COMPLETE_NEW_PASSWORD = 'COMPLETE_NEW_PASSWORD';
export const COMPLETE_NEW_PASSWORD_SUCCESS = 'COMPLETE_NEW_PASSWORD_SUCCESS';
export const COMPLETE_NEW_PASSWORD_ERROR = 'COMPLETE_NEW_PASSWORD_ERROR';

export const COMPLETE_NEW_PASSWORD_SUBMIT = 'COMPLETE_NEW_PASSWORD_SUBMIT';
export const COMPLETE_NEW_PASSWORD_SUBMIT_SUCCESS =
  'COMPLETE_NEW_PASSWORD_SUBMIT_SUCCESS';
export const COMPLETE_NEW_PASSWORD_SUBMIT_ERROR =
  'COMPLETE_NEW_PASSWORD_SUBMIT_ERROR';

export const UPDATE_USER = 'UPDATE_USER';

export const BLOCK_OBJECT = 'BLOCK_OBJECT';
export const ACTIVE_OBJECT = 'ACTIVE_OBJECT';

export const NETWORK_ONLINE = 'NETWORK_ONLINE';
export const NETWORK_OFFLINE = 'NETWORK_OFFLINE';

export const PENDING_IMAGE = 'PENDING_IMAGE';
export const RESET_PENDING = 'RESET_PENDING';

export const SHOW_INSTRUCTIONS = 'SHOW_INSTRUCTIONS';
export const HIDE_INSTRUCTIONS = 'HIDE_INSTRUCTIONS';
